blank_issues_enabled: false
contact_links:
  - name: 📚 Docs
    url: https://github.com/BetaHuhn/running-at#-usage
    about: Checkout running-at's documentation
  - name: 🚀 Feature Request
    url: https://github.com/BetaHuhn/running-at/discussions/new?category=ideas
    about: Share ideas for new features
  - name: ❓ Ask a Question
    url: https://github.com/BetaHuhn/running-at/discussions/new?category=q-a
    about: Ask the community for help