name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip-build]')"
    steps:
      - uses: actions/checkout@v2
      - uses: c-hive/gha-npm-cache@v1
      - name: Install dependencies
        run: npm install
      - name: Test
        run: npm run test
      - name: Run coverage
        run: npm run coverage
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
